import { SizeDefinition } from "./types";

export const SIZE_CATEGORIES = [
  { id: "ios", label: "iOS App Icons" },
  { id: "android", label: "Android App Icons" },
  { id: "general", label: "General" },
  { id: "favicons", label: "Favicons" },
  { id: "pwa", label: "PWA Icons" },
  { id: "apple", label: "Apple Web Icons" },
  { id: "social", label: "Social Media" },
  { id: "ms-tiles", label: "Microsoft Tiles" },
] as const;

export type CategoryId = (typeof SIZE_CATEGORIES)[number]["id"];

export const ALL_SIZES: SizeDefinition[] = [
  // ── iOS App Icons (Xcode 15+ / iOS 17–18) ──
  {
    id: "ios-appstore",
    label: "app store [1024x1024]",
    width: 1024,
    height: 1024,
    format: "png",
    filename: "ios-appstore-1024x1024.png",
    category: "ios",
  },
  {
    id: "ios-iphone-180",
    label: "iphone @3x [180x180]",
    width: 180,
    height: 180,
    format: "png",
    filename: "ios-iphone-60x60@3x.png",
    category: "ios",
  },
  {
    id: "ios-iphone-120",
    label: "iphone @2x [120x120]",
    width: 120,
    height: 120,
    format: "png",
    filename: "ios-iphone-60x60@2x.png",
    category: "ios",
  },
  {
    id: "ios-ipad-pro-167",
    label: "ipad pro @2x [167x167]",
    width: 167,
    height: 167,
    format: "png",
    filename: "ios-ipad-83.5x83.5@2x.png",
    category: "ios",
  },
  {
    id: "ios-ipad-152",
    label: "ipad @2x [152x152]",
    width: 152,
    height: 152,
    format: "png",
    filename: "ios-ipad-76x76@2x.png",
    category: "ios",
  },
  {
    id: "ios-spotlight-120",
    label: "spotlight @3x [120x120]",
    width: 120,
    height: 120,
    format: "png",
    filename: "ios-spotlight-40x40@3x.png",
    category: "ios",
  },
  {
    id: "ios-spotlight-80",
    label: "spotlight @2x [80x80]",
    width: 80,
    height: 80,
    format: "png",
    filename: "ios-spotlight-40x40@2x.png",
    category: "ios",
  },
  {
    id: "ios-settings-87",
    label: "settings @3x [87x87]",
    width: 87,
    height: 87,
    format: "png",
    filename: "ios-settings-29x29@3x.png",
    category: "ios",
  },
  {
    id: "ios-settings-58",
    label: "settings @2x [58x58]",
    width: 58,
    height: 58,
    format: "png",
    filename: "ios-settings-29x29@2x.png",
    category: "ios",
  },
  {
    id: "ios-notification-60",
    label: "notification @3x [60x60]",
    width: 60,
    height: 60,
    format: "png",
    filename: "ios-notification-20x20@3x.png",
    category: "ios",
  },
  {
    id: "ios-notification-40",
    label: "notification @2x [40x40]",
    width: 40,
    height: 40,
    format: "png",
    filename: "ios-notification-20x20@2x.png",
    category: "ios",
  },

  // ── Android App Icons (Android 13–15, Material You) ──
  {
    id: "android-playstore",
    label: "play store [512x512]",
    width: 512,
    height: 512,
    format: "png",
    filename: "android-playstore-512x512.png",
    category: "android",
  },
  {
    id: "android-xxxhdpi",
    label: "xxxhdpi [192x192]",
    width: 192,
    height: 192,
    format: "png",
    filename: "android-xxxhdpi-192x192.png",
    category: "android",
  },
  {
    id: "android-xxhdpi",
    label: "xxhdpi [144x144]",
    width: 144,
    height: 144,
    format: "png",
    filename: "android-xxhdpi-144x144.png",
    category: "android",
  },
  {
    id: "android-xhdpi",
    label: "xhdpi [96x96]",
    width: 96,
    height: 96,
    format: "png",
    filename: "android-xhdpi-96x96.png",
    category: "android",
  },
  {
    id: "android-hdpi",
    label: "hdpi [72x72]",
    width: 72,
    height: 72,
    format: "png",
    filename: "android-hdpi-72x72.png",
    category: "android",
  },
  {
    id: "android-mdpi",
    label: "mdpi [48x48]",
    width: 48,
    height: 48,
    format: "png",
    filename: "android-mdpi-48x48.png",
    category: "android",
  },
  // Adaptive Icons (foreground layer, 108dp with safe zone)
  {
    id: "android-adaptive-xxxhdpi",
    label: "adaptive xxxhdpi [432x432]",
    width: 432,
    height: 432,
    format: "png",
    filename: "android-adaptive-xxxhdpi-432x432.png",
    category: "android",
  },
  {
    id: "android-adaptive-xxhdpi",
    label: "adaptive xxhdpi [324x324]",
    width: 324,
    height: 324,
    format: "png",
    filename: "android-adaptive-xxhdpi-324x324.png",
    category: "android",
  },
  {
    id: "android-adaptive-xhdpi",
    label: "adaptive xhdpi [216x216]",
    width: 216,
    height: 216,
    format: "png",
    filename: "android-adaptive-xhdpi-216x216.png",
    category: "android",
  },
  {
    id: "android-adaptive-hdpi",
    label: "adaptive hdpi [162x162]",
    width: 162,
    height: 162,
    format: "png",
    filename: "android-adaptive-hdpi-162x162.png",
    category: "android",
  },
  {
    id: "android-adaptive-mdpi",
    label: "adaptive mdpi [108x108]",
    width: 108,
    height: 108,
    format: "png",
    filename: "android-adaptive-mdpi-108x108.png",
    category: "android",
  },

  // ── General ──
  {
    id: "general-1024",
    label: "icon [1024x1024]",
    width: 1024,
    height: 1024,
    format: "png",
    filename: "icon-1024x1024.png",
    category: "general",
  },

  // Favicons
  {
    id: "favicon-ico",
    label: "favicon.ico [16/32/48]",
    width: 48,
    height: 48,
    format: "ico",
    filename: "favicon.ico",
    category: "favicons",
    icoSizes: [16, 32, 48],
  },
  {
    id: "favicon-192",
    label: "favicon [192x192]",
    width: 192,
    height: 192,
    format: "png",
    filename: "favicon-192x192.png",
    category: "favicons",
  },
  {
    id: "favicon-512",
    label: "favicon [512x512]",
    width: 512,
    height: 512,
    format: "png",
    filename: "favicon-512x512.png",
    category: "favicons",
  },

  // PWA Icons — regular + maskable
  ...[72, 96, 128, 144, 152, 192, 384, 512].flatMap((size): SizeDefinition[] => [
    {
      id: `pwa-${size}`,
      label: `pwa [${size}x${size}]`,
      width: size,
      height: size,
      format: "png",
      filename: `pwa-${size}x${size}.png`,
      category: "pwa",
    },
    {
      id: `pwa-${size}-maskable`,
      label: `pwa maskable [${size}x${size}]`,
      width: size,
      height: size,
      format: "png",
      maskable: true,
      filename: `pwa-${size}x${size}-maskable.png`,
      category: "pwa",
    },
  ]),

  // Apple Icons
  {
    id: "apple-180",
    label: "apple touch icon [180x180]",
    width: 180,
    height: 180,
    format: "png",
    filename: "apple-touch-icon.png",
    category: "apple",
  },

  // Social Media
  {
    id: "og-image",
    label: "og image [1200x630]",
    width: 1200,
    height: 630,
    format: "png",
    filename: "og-image.png",
    category: "social",
  },
  {
    id: "twitter-image",
    label: "twitter card [1200x675]",
    width: 1200,
    height: 675,
    format: "png",
    filename: "twitter-image.png",
    category: "social",
  },

  // Microsoft Tiles
  {
    id: "ms-tile-70",
    label: "ms tile [70x70]",
    width: 70,
    height: 70,
    format: "png",
    filename: "mstile-70x70.png",
    category: "ms-tiles",
  },
  {
    id: "ms-tile-150",
    label: "ms tile [150x150]",
    width: 150,
    height: 150,
    format: "png",
    filename: "mstile-150x150.png",
    category: "ms-tiles",
  },
  {
    id: "ms-tile-310x150",
    label: "ms tile [310x150]",
    width: 310,
    height: 150,
    format: "png",
    filename: "mstile-310x150.png",
    category: "ms-tiles",
  },
  {
    id: "ms-tile-310",
    label: "ms tile [310x310]",
    width: 310,
    height: 310,
    format: "png",
    filename: "mstile-310x310.png",
    category: "ms-tiles",
  },
];

export function getSizesByCategory(categoryId: string): SizeDefinition[] {
  return ALL_SIZES.filter((s) => s.category === categoryId);
}

export function getSizeById(id: string): SizeDefinition | undefined {
  return ALL_SIZES.find((s) => s.id === id);
}
